### ISSUE TITLE
Doesn't play well with UTF-8 strings

### ISSUE THREAD

**Issue by 0xradical** [junegunn/insensitive_hash#1]
Unfortunately, the insensitivity is limited to ascii strings :(

``` ruby
require 'insensitive_hash'

h = InsensitiveHash.new
h['ç'] = 'lol'
h['Ç'] # => nil
```

Not sure if it's interesting to clutter your code with more code just to detect such things automatically, as case replacement in Ruby just occurs for characters in the ascii region.

**Comment by junegunn** [comment]
Thanks for pointing out! I haven't really thought about it before.

After a quick look up on Google, I found this gem called [unicode_utils](http://unicode-utils.rubyforge.org/) which does a great job of handling case conversions of unicode chars. However, I'm not sure at this point making it a part of this project is a good call. Ups and downs, I guess. I'll think about that.

Until I make up my mind and release a new version with unicode support, you can rely on a custom encoder.

Since version 0.3.2, you can define a custom encoder for each InsensitiveHash object, so you can make use of the aforementioned gem as follows.

``` ruby
require 'unicode_utils/downcase'

h = InsensitiveHash.new
h.encoder = proc { |key|
  case key
  when String, Symbol
    UnicodeUtils.downcase(key.to_s).gsub(' ', '_')
  else
    key
  end
}
h['ç'] = 'lol'
h['Ç'] # => 'lol'
```

Or you can just monkey-patch Hash.

``` ruby
class Hash
  def unicode_insensitive
    self.insensitive :encoder => proc { |key|
      case key
      when String, Symbol
        UnicodeUtils.downcase(key.to_s).gsub(' ', '_')
      else
        key
      end
    }
  end
end
```

Let me know if you have any suggestion.
Thanks.

**Comment by 0xradical** [comment]
The  unicode_utils gem sounds like a good option! 

Thanks for your help!
